In [106]:
import torch

In [107]:
# 1
x = torch.tensor(7)
print(x)
print("Rank: ", x.ndimension())
print("Shape: ", x.shape)

tensor(7)
Rank:  0
Shape:  torch.Size([])


In [108]:
# 2
x = torch.tensor([[1,2,3], [4,5,6]])
print(x)
print("Rank: ", x.ndimension())
print("Shape: ", x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
Rank:  2
Shape:  torch.Size([2, 3])


In [109]:
# 3
x = torch.tensor([[[1,2,3], [4,5,6]]])
print(x)
print("Rank: ", x.ndimension())
print("Shape: ", x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6]]])
Rank:  3
Shape:  torch.Size([1, 2, 3])


In [110]:
# 4
x = torch.tensor([[[[1,2,3], [4,5,6]]]])
print(x)
print("Rank: ", x.ndimension())
print("Shape: ", x.shape)

tensor([[[[1, 2, 3],
          [4, 5, 6]]]])
Rank:  4
Shape:  torch.Size([1, 1, 2, 3])


In [111]:
# 5
x = torch.tensor([[[[[1,2,3], [4,5,6]]]]])
print(x)
print("Rank: ", x.ndimension())
print("Shape: ", x.shape)

tensor([[[[[1, 2, 3],
           [4, 5, 6]]]]])
Rank:  5
Shape:  torch.Size([1, 1, 1, 2, 3])


In [112]:
# 6 . 차원 늘리기
x = torch.unsqueeze(x,0)
print(x)
print("Rank: ", x.ndimension())
print("Shape: ", x.shape)

tensor([[[[[[1, 2, 3],
            [4, 5, 6]]]]]])
Rank:  6
Shape:  torch.Size([1, 1, 1, 1, 2, 3])


In [113]:
# 7. 랭크 삭제(줄이기)
x = torch.squeeze(x)
print(x)
print("Rank: ", x.ndimension())
print("Shape: ", x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
Rank:  2
Shape:  torch.Size([2, 3])


In [114]:
# 8. 랭크 1
x.view(6)
print(x)
print("Rank: ", x.ndimension())
print("Shape: ", x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
Rank:  2
Shape:  torch.Size([2, 3])


In [116]:
try:
    x = x.view(2,4)
except Exception as e:
    print(e) #에러 출력

shape '[2, 4]' is invalid for input of size 6
